removed r_discription

diff --git a/radio b/radio
--- a/radio
+++ b/radio
@@ -15,12 +15,13 @@
 # GNU General Public License at <http://www.gnu.org/licenses/> for
 # more details.
 
-# this script for my personal purpose like playing music from various sources
-# like radio, youtube, local storage
+### discription:
+#
+# This script is for my personal purpose like playing music
+# from various sources like radio, youtube, local storage.
+# In 'select()', you can search narrowly, regex, range and default option.
 #
 # Usage: radio [name] or radio option [arg ...]
-#
-# in 'select()', you can search narrowly, regex, range and default option
 #
 # radio
 #       - plays a shuffled radio, press 'q' to play the next.
@@ -74,22 +75,26 @@
 #
 # -h | --help
 #       - prints this help.
-
-
+#
+# Exit Status:
+# Returns success unless an invalid option is given.
 
 ### TODO
 #
 # curl, google code
-# add bash, zsh, fish completion suggest for youtube-search()'s cashed phrases
+# completion suggest for radio -y -c 'cashed phrase'
+# visit the web-page playing youtube_search's result with web-browser
+# show more, show less
 
 
 
+shopt -s globstar # Allow ** for recursive matches
 set -u # avoid a undeclared variable
 g_arg=( "$@" )
 g_arg0="$0"
-PROGNAME="${g_arg0##*/}"
+PROGRAM_NAME="${g_arg0##*/}"
 BASH_VERSION='5.0.18(1)-release'
-PROGNAME_VERSION=0.1
+PROGRAM_VERSION=0.1
 PS3='
 # 00 for all
 choose : '
@@ -245,26 +250,19 @@ playing_youtube_print() {
     local arg3="$3"
     local arg4="$4"
     local arg5="$5"
-    local arg6="$6"
     local format1='\n\e[1;38;5;130m %s\e[0m\n\n'
-    local format2="\e[1;38;5;240m %s | %.2f%s%s%s%s\e[0m\n\n"
+    local format2="\e[1;38;5;240m %s | %.2f | %s | %s\e[0m\n\n"
     # test_print arg1 "$arg1"
     # test_print arg2 "$arg2"
     # test_print arg3 "$arg3"
     # test_print arg4 "$arg4"
     # test_print arg5 "$arg5"
-    # test_print arg6 "$arg6"
-    arg2=$(date -d $arg2 +%Y/%m/%d)
-    arg3=$(echo "$arg3 * 20" | bc) # float multiply
-    arg4=$(numfmt --to=si $arg4) # human-readable K,M,G,T
     printf "$format1" "$arg1" # title
-    # date, rating, count, uploader, description
     printf "$format2" \
-           "$arg2" \
-           $arg3 \
-           " | $arg4" \
-           " | $arg5" \
-           "${arg6:+$'\n'} $arg6"
+           "$(date -d $arg2 +%Y/%m/%d)" \
+           "$(echo "$arg3 * 20" | bc)" \
+           "$(numfmt --to=si $arg4 | sed 's/G/B/')" \
+           "$arg5" # date, rating, count, uploader
     return 0
 }
 
@@ -383,7 +381,7 @@ play_youtube() {
     local arg1="$1"
     local execute_part name_part
     local playing_date playing_view_count
-    local playing_average_rating playing_title
+    local playing_average_rating playing_title playing_uploader
     local pattern1 pattern2 pattern3 pattern4 pattern5 pattern6
     # test_print arg1 "$arg1"
     name_part=$(sed 's! "webpage_url":.*!!' <<< $arg1)
@@ -394,7 +392,6 @@ play_youtube() {
     pattern2='s/.*"view_count": //'
     pattern3='s/.*"title": "//'
     pattern4='s/.*"uploader": "//'
-    pattern5='s/.*"description": "//'
     pattern6='s/.*"webpage_url": "//'
     playing_date=$(grep -o '^[0-9]\{8\}' <<< $name_part)
     playing_average_rating=$(sed "$pattern1" <<< $name_part \
@@ -403,27 +400,18 @@ play_youtube() {
                              | sed 's/ "title": .*//')
     playing_title=$(sed "$pattern3" <<< $name_part \
                         | sed 's/"$//')
-    if [[ $execute_part =~ '"description": "' ]]; then
-        playing_uploader=$(sed "$pattern4" <<< $execute_part \
-                               | sed 's/" "description": .*//')
-        playing_description=$(sed "$pattern5" <<< $execute_part \
-                                  | sed 's/"$//')
-    else
-        playing_uploader=$(sed "$pattern4" <<< $execute_part \
-                               | sed 's/"$//')
-    fi
+    playing_uploader=$(sed "$pattern4" <<< $execute_part \
+                           | sed 's/"$//')
     execute_part=$(sed 's/" "uploader".*//' <<< $execute_part)
     # test_print playing_date $playing_date"
     # test_print playing_average_rating "$playing_average_rating"
     # test_print playing_view_count "$playing_view_count"
     # test_print playing_uploader "$playing_uploader"
-    # test_print playing_description "${playing_description:-}"
     playing_youtube_print "$playing_title" \
                           $playing_date \
                           $playing_average_rating \
                           $playing_view_count \
                           "$playing_uploader" \
-                          "${playing_description:-}"
     $PLAYER "$execute_part"
     return 0
 }
@@ -523,6 +511,7 @@ play_group() {
                 printf '\n         pl - Play List\n'
                 # back_trace
                 exit 2
+                ;;
         esac
     done <<< $urllist
     # test_print x $x
@@ -682,7 +671,6 @@ play_local() {
         done
     else
         locallist=
-        shopt -s globstar
         for file in "$LOCAL_MUSIC_DIR"**/*; do
             if [[ $file =~ $LOCAL_MUSIC_EXT ]]; then
                 locallist+="${locallist:+$'\n'}$file"
@@ -723,12 +711,18 @@ edit_this() {
     return 0
 }
 
+print_version() {
+    printf '\n%s\n' \
+           "$PROGRAM_VERSION"
+    return 0
+}
+
 help_usage() {
-    search_linenumber "$g_arg0" '^# Usage'
-    helplist=$(tail -n +$((x-3)) "$g_arg0")
+    search_linenumber "$g_arg0" '^# Usage: '
+    helplist=$(tail -n +$x "$g_arg0")
     search_linenumber "$helplist" ^$
     helplist=$(head -n $x <<< $helplist)
-    printf '\n %s\n' \
+    printf '\n%s\n' \
            "$(sed 's/#\+//' <<< $helplist)" # need " "
     return 0
 }
@@ -768,14 +762,15 @@ youtube_search() {
     # uses youtube-dl json-dump
     #
     local s_phrase="${g_arg[@]:1}"
-    local s_limit=100 # it takes 8 secs for getting 10 items, so need cache
+    local s_limit=100 # it takes 8 secs to get 10 items, so need cache
     local max_cache=10000000
     local display_c_Phrase_limit=100 # modify later
     local try_dump_limit=1000
-    local result r_list
-    local r_date r_count r_rating
-    local r_title r_url r_description
-    local arr_title arr_url
+    local result=
+    local r_list r_date r_rating r_count
+    local r_title r_url r_uploader r_description
+    local arr_date arr_rating arr_count
+    local arr_title arr_url arr_uploader arr_description
     local c_phrase s_rate d_phrase d_matched u_matched
     local lastline lastdate dots
     local i=0 j=0 c=0
@@ -867,7 +862,7 @@ youtube_search() {
                        'Fail dumping. try later!'
                 exit 66
             fi
-            printf '\r%s\e[1;38;5;40m %s\e[1;38;5;117m %s\e[0m' \
+            printf '\e[1;38;5;117m%s\e[0m %s\e[1;38;5;40m %s\e[0m\r' \
                    $c \
                    'trying' \
                    $dots
@@ -895,7 +890,39 @@ youtube_search() {
             arr_search+=( ["$s_phrase"]=1 )
         fi
     fi
-    # can add : id, duration, like, dislike ...
+    #
+    # json_order:
+    #
+    # "id":
+    # "uploader"
+    # "uploader_id"
+    # "uploader_url"
+    # "channel_id"
+    # "channel_url"
+    # "upload_date"
+    # "license"
+    # "creator"
+    # "title"
+    # "alt_title"
+    # "thumbnails"
+    # "description"
+    # "categories"
+    # "tags"
+    # "subtitles"
+    # "automatic_captions"
+    # "duration"
+    # "age_limit"
+    # "annotations"
+    # "chapters"
+    # "webpage_url"
+    # "view_count"
+    # "like_count"
+    # "dislike_count"
+    # "average_rating"
+    # "formats"
+    #
+    # basic regex escape ‘\?’, ‘\+’, ‘\|’, ‘\{’, '\}', ‘\(’, and ‘\)’
+    #
     r_date=$(grep -oP '"upload_date": ".*?",' <<< $result \
                  | sed 's/^".*": "//' \
                  | sed 's/",$//') # for sort
@@ -909,24 +936,32 @@ youtube_search() {
                 | sed 's/,$//')
     r_uploader=$(grep -oP '"uploader": ".*?",' <<< $result \
                      | sed 's/,$//')
-    r_description=$(grep -oP '"description": ".*?",' <<< $result \
-                        | sed 's/,$//')
     readarray -t arr_date <<< $r_date # first position
     readarray -t arr_rating <<< $r_rating
     readarray -t arr_count <<< $r_count
     readarray -t arr_title <<< $r_title
     readarray -t arr_url <<< $r_url
     readarray -t arr_uploader <<< $r_uploader
-    readarray -t arr_description <<< $r_description # last position
+    # test_print arr_date ${#arr_date[@]}
+    # test_print arr_rating ${#arr_rating[@]}
+    # test_print arr_count ${#arr_count[@]}
+    # test_print arr_url ${#arr_url[@]}
+    # test_print arr_title ${#arr_title[@]}
+    # test_print arr_uploader ${#arr_uploader[@]}
+    if (( ${#arr_title[@]} != ${#arr_url[@]} )); then
+        printf "\n %s\n %s\n %s\n" \
+               "tittles: ${#arr_title[@]}" \
+               "urls:    ${#arr_url[@]}" \
+               'sync fails!'
+    fi
     for title in "${arr_title[@]}"; do
-        r_list+=$(printf "${r_list:+\n}%s %s %s %s %s %s%s" \
+        r_list+=$(printf "${r_list:+\n}%s %s %s %s %s %s" \
                          "${arr_date[$i]}" \
                          "${arr_rating[$i]}" \
                          "${arr_count[$i]}" \
-                         "$title" \
+                         "${arr_title[$i]}" \
                          "${arr_url[$i]}" \
-                         "${arr_uploader[$i]}" \
-                         "${arr_description[$i]:+ }${arr_description[$i]:-}")
+                         "${arr_uploader[$i]}")
         ((i++))
     done
     r_list=$(sort <<< $r_list)
@@ -961,11 +996,12 @@ case "${g_arg[0]:-}" in
     -a | --all     ) show_all       && exit 0;;
     -g | --group   ) play_group     && exit 0;;
     -l | --local   ) play_local     && exit 0;;
-    -t | --test    ) test_items     && exit 0;;
-    -e | --edit    ) edit_this      && exit 0;;
-    -h | --help    ) help_usage     && exit 0;;
     -x | --xxx     ) play_xxx       && exit 0;;
     -y | --youtube ) youtube_search && exit 0;;
+    -t | --test    ) test_items     && exit 0;;
+    -e | --edit    ) edit_this      && exit 0;;
+    -v | --version ) print_version  && exit 0;;
+    -h | --help    ) help_usage     && exit 0;;
     -*)
         printf '\n %s\e[1;31m %s\e[0m %s\n' \
                'There is no' \
@@ -979,8 +1015,10 @@ case "${g_arg[0]:-}" in
         printf '\n         -y [option] [phrase] searches a phrase in youtube'
         printf '\n         -t tests all radios'
         printf '\n         -e edit this script.'
+        printf '\n         -h prints version'
         printf '\n         -h prints help\n'
-        exit 2;;
+        exit 2
+        ;;
 esac
 make_namelist "$urllist"
 input_lines=$(grep -v "$SKIP_PATTERN" <<< $input_lines \
